# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file (if any)
COPY requirements.txt .

# Install dependencies (if any)
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python script into the container
COPY ami-client.py .

# Run the Python script when the container starts
CMD ["python", "ami-client.py"]